### ISSUE TITLE
Merge plugins ?

### ISSUE THREAD

**Issue by bleutzinn** [jgonyea/grav-plugin-one-time-login#2]
To me your plugin seems safe and elegant. Very nice.

Instead of using the command line, I wanted the user to be able to generate a One Time Login link and have it send to him or her by email. That's why I wrote a new plugin named [One Time Login Mailer](https://github.com/bleutzinn/grav-plugin-one-time-login-mailer).

It is still a bit rough since all configuration is hard coded in the plugin PHP code. But that is on purpose.  First I would like to know whether or not you would like to merge these two plugins. Or in other words would like to add the email feature to your plugin to make it usable to a wider audience.

Please let me know what you think of this.

**Comment by jgonyea** [comment]
Hi! Thanks for your interest.  How do you see your One Time Login Mailer being functionally different than the Forgot Password link in the login plugin?

**Comment by bleutzinn** [comment]
First I think a one time password is a very user friendly way to provide known users access.
Secondly there is no need to even store a password in the user account file which also eliminates the need for a full blown registration process although the Login Plugin does provide that of course.
Lastly, I'm sure the Login Plugin supports a password reset and sending a password forgot email but how is  not documented, at least I couldn't find it.

So all in all I think installing and configuring our plugins is a lot simpler.

**Comment by jgonyea** [comment]
You can feel free to use my plugin as a dependency, but I don't think I want to merge anything as of right now.
